---

- hosts: [kibana_server]
  roles:
    - { role: elasticsearch, es_instance_name: "node1", es_heap_size: "1g",
      es_config: {
        cluster.name: "SimpleIT",
        network.host: "{{ ansible_hostname }}",
        discovery.zen.ping.unicast.hosts: "{{ groups['elastic_servers'] | join(',') }}",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: false,
        bootstrap.mlockall: true
      }
    }
    - { role: kibana,
        kibana_server_port: 5601,
        kibana_server_host: "0.0.0.0",
        kibana_elasticsearch_url: "http://{{ inventory_hostname }}:9200"
    }
        

  environment:
      http_proxy: http://10.144.1.10:8080
      https_proxy: http://10.144.1.10:8080
  vars:
    proxy_server: "http://10.144.1.10:8080"
    ansible_become: true
    es_version: "2.4.0"
    es_plugins:
      - plugin: license
      - plugin: marvel-agent
    proxy_env:
      http_proxy: "{{ proxy_server }}"
      https_proxy: "{{ proxy_server }}"

  tasks:
    - name: Downloading Marvel plugin.
      get_url:
        url: "https://download.elastic.co/elasticsearch/marvel/marvel-latest.tar.gz"
        dest: "{{ ansible_env.HOME}}"

    - name: Installing Marvel plugin.
      shell: /opt/kibana/bin/kibana plugin --install marvel -u file:///{{ ansible_env.HOME}}/marvel-latest.tar.gz

