---

- hosts: [web_servers]
 
  roles:
    - role: nginx
      nginx_sites:
        elastic:
          - listen 8080
          - location / { 
              auth_basic "Protected Elasticsearch";
              auth_basic_user_file /etc/nginx/passwords;
              proxy_pass http://elasticsearch;
              proxy_http_version 1.1;
              proxy_set_header Connection "Keep-Alive";
              proxy_set_header Proxy-Connection "Keep-Alive";
            }
      nginx_configs:
        upstream:
          - upstream elasticsearch { 
            {% for host in groups['elastic_servers'] %}
                server {{ hostvars[host].inventory_hostname }}:9200;
            {% endfor %}
            } 
  
  environment:
      http_proxy: http://10.144.1.10:8080
      https_proxy: http://10.144.1.10:8080
  vars:
    proxy_server: "http://10.144.1.10:8080"
    ansible_become: true
    proxy_env:
      http_proxy: "{{ proxy_server }}"
      https_proxy: "{{ proxy_server }}"
